### ISSUE TITLE
Not compatible with React 18.2.0 (latest version)

### ISSUE THREAD

**Issue by talent1223** [eBayClassifiedsGroup/react-advertising#83]
I tried to install this package in my React project(using React 18.2.0) but not able to do that.
Because this is not compatible with React version 18.2.0.
Please let me know how to fix it.

**Comment by tomattone** [comment]
Me too 😢

**Comment by matt-odk** [comment]
The issue should have been resolved now, restriction has been removed from the package.json in [this commit](https://github.com/eBayClassifiedsGroup/react-advertising/commit/25cbc044336957cbe79f961935422da558839308)

**Comment by MisterJimson** [comment]
@jdw1996 can you double check compatibility with 18.2.0 and close this afterwards assuming we are good?

**Comment by jdw1996** [comment]
Thanks for pointing out the update to `peerDependencies` @matt-odk! I believe you are right, this should no longer be a problem. I just created a new React 18 project with Create React App and I was able to install `react-advertising` without issue. If you notice any further compatibility problems in the future, please let us know!
